### ISSUE TITLE
Multi-processes Exec Mode

### ISSUE THREAD

**Issue by fjribi** [cadCAD-org/cadCAD#104]
Hello,

When trying to run "BlockScience/ZarghamPapers" notebooks locally (anaconda/windows), I got some errors when using multiprocessor execution mode. (see:[https://github.com/BlockScience/ZarghamPapers/issues/1]). This could be a generic issue for cadCAD.
Do you have any feedback on the subject?

Regards,

**Comment by markusbkoch** [comment]
Thank you! We'll look into it as soon as possible. In the meantime I just want to flag that this and #93 might be related.

**Comment by fjribi** [comment]
Yes, I confirm, in my workaround used  
`dill.settings['trace'] = True`
that fixes the problem 
I also think that it's a windows specific issue...

**Comment by mzargham** [comment]
@fjribi  Thanks for sharing. 

adding an FYI to contributors @JEJodesty @markusbkoch @danlessa @tylerdmace; we're a pretty small team and this particular repo isn't watched as closely as the main \cadCAD repo which contains the engine itself.

**Comment by fjribi** [comment]
Thank you for your reactivity. My remaining question is whether it's convenient to add the "workaround code" at the [ENV]\Lib\site-packages\cadCAD_init_.py file as I suggested or do you recommend another location? (in order to fixe it for all cadCAD projects in the current environment)?

```
import os
if os.name == 'nt': #to check if we are running on windows
    import dill
    dill.settings['recurse'] = True 
```

**Comment by mzargham** [comment]
That sounds fine to me but for a final answer, I defer to @markusbkoch and/or @JEJodesty.

**Comment by JEJodesty** [comment]
@fjribi 
Steps:
1. PR your solution to `staging`
2. PR to `merge_stage`
we will discuss the diff together

**Comment by JEJodesty** [comment]
personal note
https://github.com/BlockScience/ZarghamPapers/issues/1

**Comment by fjribi** [comment]
ok

**Comment by fjribi** [comment]
Hi, 

Please do not hesitate if you have any questions concerning my PR...

**Comment by JEJodesty** [comment]
@fjribi Accidentally merged PR #105. Can you please submit a new one with the same content.
:'(

**Comment by JEJodesty** [comment]
@fjribi Putting eyes one this now

**Comment by JEJodesty** [comment]
@fjribi essentially You submitted a proposal and with the files you've changed
please submit a PR with your modification, it was missing #105

**Comment by tylerdmace** [comment]
I'm looking into this now.

**Comment by tylerdmace** [comment]
PR #118 has been merged. Thanks for the contribution, @fjribi
