### ISSUE TITLE
Fix link from Simulation Configuration to Simulation Execution page

### ISSUE THREAD

**Issue by JGBSci** [cadCAD-org/cadCAD#142]
The link underlying the word "Executed" on the following page gives a 414 error:

https://github.com/cadCAD-org/cadCAD/blob/master/documentation/README.md

It should presumably link to the Simulation Execution page:

https://github.com/cadCAD-org/cadCAD/blob/master/documentation/Simulation_Execution.md

**Comment by tylerdmace** [comment]
Created new PR with this work that targeted the correct base. See #161

**Comment by JEJodesty** [comment]
@tylerdmace 
Merged
