### ISSUE TITLE
Fix typo on Simulation Execution page

### ISSUE THREAD

**Issue by JGBSci** [cadCAD-org/cadCAD#143]
"Example Simulation Executions:" under Execution Examples should be on a new line

https://github.com/cadCAD-org/cadCAD/blob/master/documentation/Simulation_Execution.md

**Comment by markusbkoch** [comment]
I'm not entirely sure what you mean. Wanna take a shot at editing it yourself and starting a pull request? 😉  Let me know if you need help!

**Comment by tylerdmace** [comment]
Fixed in #160

**Comment by JEJodesty** [comment]
@tylerdmace 
Merged
