### ISSUE TITLE
Getting the same results while running multiple simulations

### ISSUE THREAD

**Issue by santteegt** [cadCAD-org/cadCAD#144]
Hello,

I'm running an updated version of `robot-marbles-part-4.ipynb` notebook from the old repository so it is compatible with the latest version of the library however I'm getting the same results on every simulation when running with N  > 1. Seems that the error starts in the following line:

https://github.com/cadCAD-org/cadCAD/blob/d422ff9f51fa0107c1a5a419b9a6df5beac09676/cadCAD/engine/__init__.py#L146

This does not happen If you send the `Ns` variable instead of the `RunIDs` as the last parameters. However, the `run` columns get wrong values and the `timestep` column doesn't match with the results of each simulation

**Comment by markusbkoch** [comment]
Thanks @santteegt . That's being worked on and should be fixed in an upcoming release.

**Comment by JEJodesty** [comment]
linked to #165

**Comment by JEJodesty** [comment]
Resolved
