### ISSUE TITLE
Pool not running error when running A/B testing

### ISSUE THREAD

**Issue by santteegt** [cadCAD-org/cadCAD#145]
Hello,

I'm running an updated version of `robot-marbles-part-6.ipynb` notebook from the old repository so it is compatible with the latest version of the library, however, I'm getting the following error when trying to run the A/B testing simulation:

```
Configurations Length: 2
Execution Method: parallelize_simulations
Execution Mode: parallelized
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-ff051015a8c7> in <module>
      1 # %%capture
      2 results = []
----> 3 for raw_result, tensor, _ in executor.execute():
      4     df = pd.DataFrame(raw_result)
      5     results.append(df)

~/anaconda3/envs/cadcad/lib/python3.8/site-packages/cadCAD/engine/__init__.py in execute(self)
    127 
    128             print("Execution Method: " + self.exec_method.__name__)
--> 129             simulations_results = self.exec_method(
    130                 sim_executors, var_dict_list, states_lists, configs_structs, env_processes_list, Ts, SimIDs, RunIDs #Ns
    131             )

~/anaconda3/envs/cadcad/lib/python3.8/site-packages/cadCAD/engine/execution.py in parallelize_simulations(simulation_execs, var_dict_list, states_lists, configs_structs, env_processes_list, Ts, SimIDs, Ns)
     80     len_new_configs_structs = len(new_configs_structs)
     81     pp = PPool(len_new_configs_structs)
---> 82     results = flatten(pp.map(lambda params: threaded_executor(params), new_params))
     83     pp.close()
     84     return results

~/anaconda3/envs/cadcad/lib/python3.8/site-packages/pathos/multiprocessing.py in map(self, f, *args, **kwds)
    135         AbstractWorkerPool._AbstractWorkerPool__map(self, f, *args, **kwds)
    136         _pool = self._serve()
--> 137         return _pool.map(star(f), zip(*args)) # chunksize
    138     map.__doc__ = AbstractWorkerPool.map.__doc__
    139     def imap(self, f, *args, **kwds):

~/anaconda3/envs/cadcad/lib/python3.8/site-packages/multiprocess/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

~/anaconda3/envs/cadcad/lib/python3.8/site-packages/multiprocess/pool.py in _map_async(self, func, iterable, mapper, chunksize, callback, error_callback)
    471         Helper function to implement map, starmap and their async counterparts.
    472         '''
--> 473         self._check_running()
    474         if not hasattr(iterable, '__len__'):
    475             iterable = list(iterable)

~/anaconda3/envs/cadcad/lib/python3.8/site-packages/multiprocess/pool.py in _check_running(self)
    348     def _check_running(self):
    349         if self._state != RUN:
--> 350             raise ValueError("Pool not running")
    351 
    352     def apply(self, func, args=(), kwds={}):

ValueError: Pool not running
```

**Comment by BenSchZA** [comment]
Hey @santteegt ! Could you provide a copy of the notebook or Python script you're using? Maybe it's an issue with the execution mode `Execution Mode: parallelized`. Could you try one of the alternative execution modes mentioned here, like `local_mode`? https://github.com/cadCAD-org/cadCAD/blob/master/documentation/Simulation_Execution.md

**Comment by markusbkoch** [comment]
@jzaki was [running into this too](https://github.com/cadCAD-org/demos/issues/1#issuecomment-657483572) when updating the tutorial. I switched to `local_mode`, but have a different error I can't seem to find the source of. I've attached a stripped down version of the part-6 notebook as a python script in this txt file: [robot-marbles-part-6.txt](https://github.com/cadCAD-org/cadCAD/files/4933833/robot-marbles-part-6.txt)

cc @JEJodesty 

```
$ python3 robot-marbles-part-6.py 
                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD
Execution Mode: local_proc
Configuration Count: 100
Dimensions of the first simulation: (Timesteps, Params, Runs, Vars) = (10, 1, 1, 2)
Execution Method: local_simulations
Traceback (most recent call last):
  File "robot-marbles-part-6.py", line 98, in <module>
    sys_model_AB_raw_result, sys_model_AB_tensor_field, sessions = sys_model_AB_simulation.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cadCAD/engine/__init__.py", line 140, in execute
    final_result = get_final_results(simulations_results, partial_state_updates, eps, sessions, remote_threshold)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cadCAD/engine/__init__.py", line 104, in get_final_results
    for sim_result, psu, ep in list(zip(simulations, psus, eps)):
TypeError: zip argument #1 must support iteration
```

**Comment by santteegt** [comment]
Hi @BenSchZA 

Neither local_mode nor multi_proc worked. Here's the notebook I'm using: https://gist.github.com/santteegt/3e9462eff34179a57aaf4e5b3a52f8f7

**Comment by matttyb80** [comment]
If you change N to 49 instead of 50, it should run. There is a remote_threshold = 100 for the number of configurations, that is preventing the simulation from executing.

**Comment by markusbkoch** [comment]
> Neither local_mode nor multi_proc worked. Here's the notebook I'm using: https://gist.github.com/santteegt/3e9462eff34179a57aaf4e5b3a52f8f7

There are a few different things that came up in the process of updating the tutorials to 0.4.17. In your gist I see that you are not using `config_sim` which seems to have been made mandatory (see [this review](https://github.com/cadCAD-org/cadCAD/pull/148#discussion_r454435504))

[This is the latest version of R&M-part6](https://github.com/cadCAD-org/demos/commit/36b506fce465e03d9128df9a515a267748127ddb/) (work in progress). It won't run in 0.4.17 because of #155, unless you comment out the first call to `execute` (and everything that depends on it), which should be fine for learning purposes since it's just a recap of part 4.

**Comment by markusbkoch** [comment]
> If you change N to 49 instead of 50, it should run. There is a remote_threshold = 100 for the number of configurations, that is preventing the simulation from executing.

Great catch, thanks! I've opened #156 to handle this. I think we've learned a few things in this thread, some of which have been addressed in the comments and others which will be handled in a future release and have been broken down into their own threads, so I'm closing this issue for now.
