### ISSUE TITLE
Error when calling execute() twice in parallelized execution mode

### ISSUE THREAD

**Issue by markusbkoch** [cadCAD-org/cadCAD#155]
## How to reproduce
Duplicate [line 15 of the sys_model_AB_exec example](https://github.com/cadCAD-org/cadCAD/blob/fc33855/documentation/examples/sys_model_AB_exec.py#L15)
```
config_names = ['sys_model_A', 'sys_model_B']
sys_model_AB_raw_result, sys_model_AB_tensor_field, sessions = sys_model_AB_simulation.execute()
sys_model_AB_raw_result, sys_model_AB_tensor_field, sessions = sys_model_AB_simulation.execute()
sys_model_AB_result = pd.DataFrame(sys_model_AB_raw_result)
```

## Output
```
$ python3 documentation/examples/sys_model_AB_exec.py 

                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

Execution Mode: local_proc
Configuration Count: 4
Dimensions of the first simulation: (Timesteps, Params, Runs, Vars) = (1, 1, 1, 5)
Execution Method: local_simulations
Execution Mode: parallelized
Total execution time: 0.12s

                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

Execution Mode: local_proc
Configuration Count: 4
Dimensions of the first simulation: (Timesteps, Params, Runs, Vars) = (1, 1, 1, 5)
Execution Method: local_simulations
Execution Mode: parallelized
ValueError: sim_configs' N must > 0
Traceback (most recent call last):
  File "documentation/examples/sys_model_AB_exec.py", line 16, in <module>
    sys_model_AB_raw_result, sys_model_AB_tensor_field, sessions = sys_model_AB_simulation.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cadCAD/engine/__init__.py", line 140, in execute
    final_result = get_final_results(simulations_results, partial_state_updates, eps, sessions, remote_threshold)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cadCAD/engine/__init__.py", line 104, in get_final_results
    for sim_result, psu, ep in list(zip(simulations, psus, eps)):
TypeError: zip argument #1 must support iteration

```

## Investigation
The print statement `ValueError: sim_configs' N must > 0` shown in the output above is being generated by this [exception handling bit of code](https://github.com/cadCAD-org/cadCAD/blob/cb68b1a/cadCAD/engine/execution.py#L109), which seems to be masking the problem and allowing execution to continue when it should have been halted. Replacing the print statement with a `raise` shows that the `ValueError` exception is being raised by [this line](https://github.com/cadCAD-org/cadCAD/blob/cb68b1a/cadCAD/engine/execution.py#L83) in `execution.py`:
`results = flatten(pp.map(lambda params: threaded_executor(params), new_params))`

Apparently, this is due to the fact that the pool that was instantiated the first time `execute` was called is being reused on the second call to `execute`. See this comment in the [pathos repo](https://github.com/uqfoundation/pathos/issues/111#issuecomment-397462354):
>pathos persists it's pools in an internal registry... so that if you create a pool that is "the same" as a previous pool (i.e. same number of nodes, same other configuration parameters), it reuses the old one instead of creating a new pool instance. Hence, you either have to restart an old pool instance that has been "closed", or you have to "delete" the old instance from the registry.

Adding a few lines of code to `execution.py` try to restart the pool in case it already exists seems to solve the problem
```
pp = PPool()
# NEW: try to restart the pool
try:
    pp.restart()
except:
    pass #maybe do something?
# \NEW
results = flatten(pp.map(lambda params: threaded_executor(params), new_params))
```

**Comment by JEJodesty** [comment]
@markusbkoch @sembrestels 
Solved calling execute() twice & great catch with `PPool`!
Just added & Both will be in next release
Will go.with something below that will execute without `PPool` if `pp.restart()` throws an errors
```
results = None
    pp = PPool()
    try:
        pp.restart()
    except:
        results = flatten(list(map(lambda params: threaded_executor(params), new_params)))
    if results is None:
        results = flatten(pp.map(lambda params: threaded_executor(params), new_params))

    return results
```

**Comment by JEJodesty** [comment]
@markusbkoch @sembrestels 
Solved calling execute() twice & great catch with `PPool`!
Just added & Both will be in next release
Will go.with something below that will execute without `PPool` if `pp.restart()` throws an error
```
results = None
    pp = PPool()
    try:
        pp.restart()
    except:
        results = flatten(list(map(lambda params: threaded_executor(params), new_params)))
        
    if results is None:
        results = flatten(pp.map(lambda params: threaded_executor(params), new_params))

    return results
```

**Comment by JEJodesty** [comment]
@markusbkoch @sembrestels 
1) Solved calling execute() twice & 2) great catch with `PPool`!
Just added & Both will be in next release

@sembrestels 
Thought about restart but i prefer the 2nd option suggested in the same comment.
'"delete" the old instance from the registry'
by
`close` (close the pool to any new jobs)
`join` (cleanup the closed worker processes)
`clear` (Remove server with matching state)

because i would like to keep process pools distinct as seen in the code and not be represented the same instance in registry

**Comment by JEJodesty** [comment]
linked to #165

**Comment by JEJodesty** [comment]
Resolved
