### ISSUE TITLE
Remove remote_threshold limit or let the user override it

### ISSUE THREAD

**Issue by markusbkoch** [cadCAD-org/cadCAD#156]
First mentioned in https://github.com/cadCAD-org/cadCAD/issues/145#issuecomment-660323074

As @matttyb80 said somewhere else we would like the ability to override the limit, since config count is not indicative of a memory/time overload. Also would want the error handling for this to be more explicit ([this is the current behavior](https://github.com/cadCAD-org/cadCAD/issues/145#issuecomment-659627462))

**Comment by matttyb80** [comment]
For completeness regarding error handling, the error message of "TypeError: zip argument #1 must support iteration" that @markusbkoch posted above is for local_mode execution context.
If execution context is mutli_proc, the error message is "TypeError: 'NoneType' object is not iterable"
![image](https://user-images.githubusercontent.com/33430774/87855380-cff18780-c8e5-11ea-900f-c98480c03b0f.png)

**Comment by JEJodesty** [comment]
@markusbkoch 
will be temporarily removed in next release

**Comment by JEJodesty** [comment]
linked to #165
