### ISSUE TITLE
config_sim and append_configs should not mutate mutable reference arguments

### ISSUE THREAD

**Issue by markusbkoch** [cadCAD-org/cadCAD#157]
We often reuse previously defined variables related to the system we're modelling. See for example the [original robot and marbles tutorial part 6](https://github.com/cadCAD-org/cadCAD/blob/os_release/tutorials/robot-marbles-part-6/robot-marbles-part-6.ipynb) how in cell 6 we reuse `simulation_parameters` originally defined in cell 1 and used in cell 2.

The new `config_sim` and `append_configs` implementations modify the content of the variables passed to them as arguments
![image](https://user-images.githubusercontent.com/34865315/87855951-1947d400-c8f2-11ea-93e8-882015f6e1a1.png)

I might be missing something and maybe there's a more straightforward workaround, but it seems this means that we now need to redefine and pre-process the same configuration before each append_config, [like here](https://github.com/cadCAD-org/demos/blob/36b506fce465e03d9128df9a515a267748127ddb/tutorials/robot-marbles-part-6/robot-marbles-part-6.ipynb). In any case, seems this could be avoided by implementing `config_sim` and `append_configs` so that they don't mutate mutable reference arguments.
![image](https://user-images.githubusercontent.com/34865315/87856160-8ad45200-c8f3-11ea-946d-4931f71462c6.png)

**Comment by JEJodesty** [comment]
@markusbkoch 
Good Catch!
A Configuration Object should be implemented to eliminate the risk of Configurations being mutated between experiments unwantedly
Will Define

**Comment by JEJodesty** [comment]
@markusbkoch 
Jira issue related to this was created a few months ago. Referencing within.

**Comment by emanuellima1** [comment]
Needs refinement, low priority.

**Comment by danlessa** [comment]
This functionality was deprecated by the usage of Experiment instances
