### ISSUE TITLE
 0.4.19 Staging release

### ISSUE THREAD

**Issue by matttyb80** [cadCAD-org/cadCAD#177]
File "C:\Users\mbarl\AppData\Local\Continuum\anaconda3\lib\site-packages\cadCAD\engine\simulation.py", line 39, in policy_scope_tuner     return f(sweep_dict, sub_step, sL, s, kwargs_1=None) TypeError: p_marketing_rate() got an unexpected keyword argument 'kwargs_1'

Working  experiment in version 0.4.18: https://github.com/matttyb80/adoption_funnel 
Viewed in notebook: https://github.com/matttyb80/adoption_funnel/blob/master/adoption_funnel.ipynb

Error in 0.4.19, same model new branch: https://github.com/matttyb80/adoption_funnel/tree/4.19
Viewed in notebook: https://github.com/matttyb80/adoption_funnel/blob/4.19/adoption_funnel.ipynb

**Comment by BenSchZA** [comment]
Hey @matttyb80! v0.4.19 introduces an additional variable length argument `**kwargs` to all policy and state update functions, I'm assuming as a way to introduce new cadCAD features down the line:

`p_marketing_rate(params, substep, state_history, prev_state)` -> `p_marketing_rate(params, substep, state_history, prev_state, **kwargs)`

**Comment by matttyb80** [comment]
Thanks @BenSchZA ! You are correct. This does introduce a backwards compatibility issue. But we can move forward with enforcement of this requirement if necessary.

**Comment by JEJodesty** [comment]
It was introduced in 0.4.18

@BenSchZA 
Correct, but it shouldn't require **kwargs. 

@matttyb80 
It should be optional / backwards compatible.
If its not difficult, move forward with enforcement but i will fix it in a release around EoW

**Comment by matttyb80** [comment]
Except that it does require passing **kwargs in the policy functions.
Does not yet require passing **kwargs in the variable functions. 
That is to say, now runs by refactoring policy functions and not variable functions.

**Comment by JEJodesty** [comment]
@matttyb80 @BenSchZA 
Then i can simply revert the merge and only include the changes for the hot fix
I corrupted master with dev i though was ok.
My bad yall

**Comment by JEJodesty** [comment]
This issue exists in `staging`

**Comment by JEJodesty** [comment]
@matttyb80 @BenSchZA @aclarkData 
try it now
1.
reinstall cadCAD
Option B: Build From Source
https://github.com/cadCAD-org/cadCAD/tree/hot_fix

**Comment by BenSchZA** [comment]
I think this can be closed.
