### ISSUE TITLE
0.4.21 run column isn't showing unique results

### ISSUE THREAD

**Issue by aclarkData** [cadCAD-org/cadCAD#186]
As can be seen in the following simulation result, when running monte carlo runs with cadCAD 0.4.21, when subsetting runs by the run column, there is no difference between the runs, even when stochastic processes are present. This issue has been present since cadCAD 0.4.17 I believe. Please help

https://gitlab.com/grassrootseconomics/cic-modeling/-/blob/cadCAD_upgrade/Simulation/CIC_Network_cadCAD_model.ipynb

![image](https://user-images.githubusercontent.com/15710720/91729107-0e7b9280-eb72-11ea-8a80-c9a8a251eecc.png)

**Comment by matttyb80** [comment]
This probably doesn't fix the issue- but I do not believe this is run 0.4.21 (Looking at your economyconfig.py, still imports append_configs instead of Experiment)

**Comment by aclarkData** [comment]
@matttyb80 Were you on the cadCAD_upgrade branch? It looks like I'm using experiment? https://gitlab.com/grassrootseconomics/cic-modeling/-/blob/cadCAD_upgrade/Simulation/model/economyconfig.py

**Comment by matttyb80** [comment]
I see it now. A stray click switches you to master branch in git lab, I see.

**Comment by matttyb80** [comment]
I did run it in the new branch and am getting unique results.
![image](https://user-images.githubusercontent.com/33430774/91740761-ba78aa00-eb81-11ea-8d3f-85982cb0b560.png)

**Comment by aclarkData** [comment]
That is so weird. I just "pip freeze | grep cadCAD     cadCAD==0.4.21" 

![image](https://user-images.githubusercontent.com/15710720/91741215-64583680-eb82-11ea-96be-8c2d56d33c67.png)
And I'm still getting the same results. I wonder why it isn't working on my machine?

**Comment by JEJodesty** [comment]
@aclarkData 
@matttyb80 
Python versions?

**Comment by aclarkData** [comment]
Python 3.8.3

**Comment by JEJodesty** [comment]
@aclarkData Linux
@matttyb80 Windows

**Comment by aclarkData** [comment]
I'm seeing variability within monte Carlo runs when using parameter sweeps. When I'm NOT using param sweeps, I'm not seeing the variability.

**Comment by markusbkoch** [comment]
I'm having the same issue when I run the CIC notebook  
MacOS 10.14.6
Python 3.7.5  
cadCAD 0.4.21  

![image](https://user-images.githubusercontent.com/34865315/92154122-acce5900-edfb-11ea-8992-357822a17a0a.png)

**Comment by markusbkoch** [comment]
[This comment](https://github.com/cadCAD-org/demos/pull/2/#discussion_r482317338) is probably related ([notebook](https://github.com/jzaki/demos/blob/87953bc4c7abe6ee8fd22d4af8a147952650d7c4/tutorials/robot-marbles-part-4/robot-marbles-part-4.ipynb)) 
![image](https://user-images.githubusercontent.com/34865315/92154421-27977400-edfc-11ea-9a7a-331de9a7365f.png)

**Comment by BenSchZA** [comment]
I recreated the issue here I think, with minimal code, and printed some extra debug details too: https://gist.github.com/BenSchZA/72b1b0a529703e97cd4e53f200e1516b

macOS 10.15.6
Python 3.8.5
cadCAD 0.4.21

**Comment by JEJodesty** [comment]
remove the plotting functions
```
Total execution time: 52.77s
Run one: 1308    1.995921
1309    1.995921
1310    1.995921
1311    1.995921
1312    0.663139
Name: VelocityOfMoney, dtype: float64
Run two: 1409    0.591588
1410    0.591588
1411    0.591588
1412    0.591588
1413    1.390478
Name: VelocityOfMoney, dtype: float64
Run three: 1510    1.084336
1511    1.084336
1512    1.084336
1513    1.084336
1514    3.002238
Name: VelocityOfMoney, dtype: float64
```

**Comment by JEJodesty** [comment]
@aclarkData 
Next, 
Why is this causing a mutation?

**Comment by BenSchZA** [comment]
> I recreated the issue here I think, with minimal code, and printed some extra debug details too: https://gist.github.com/BenSchZA/72b1b0a529703e97cd4e53f200e1516b
> 
> macOS 10.15.6
> Python 3.8.5
> cadCAD 0.4.21

@JEJodesty this minimal example has the same issue (as far as I can see), and doesn't seem to have anything out of the ordinary that could be causing mutations.

**Comment by JEJodesty** [comment]
@BenSchZA @aclarkData @matttyb80 @markusbkoch 
Solved

@markusbkoch 
It was multi processing
removed it and kept multithreading and it worked

```
Total execution time: 0.03s
Run one: 
+----+----------+--------------+----------+-------+-----------+------------+
|    |        a |   simulation |   subset |   run |   substep |   timestep |
|----+----------+--------------+----------+-------+-----------+------------|
|  0 |  0       |            0 |        0 |     1 |         0 |          0 |
|  1 |  5.52521 |            0 |        0 |     1 |         1 |          1 |
|  2 |  5.68298 |            0 |        0 |     1 |         1 |          2 |
|  3 | 12.7897  |            0 |        0 |     1 |         1 |          3 |
+----+----------+--------------+----------+-------+-----------+------------+
Run two: 
+----+----------+--------------+----------+-------+-----------+------------+
|    |        a |   simulation |   subset |   run |   substep |   timestep |
|----+----------+--------------+----------+-------+-----------+------------|
|  4 | 0        |            0 |        0 |     2 |         0 |          0 |
|  5 | 0.639853 |            0 |        0 |     2 |         1 |          1 |
|  6 | 1.80996  |            0 |        0 |     2 |         1 |          2 |
|  7 | 6.69687  |            0 |        0 |     2 |         1 |          3 |
+----+----------+--------------+----------+-------+-----------+------------+
Run three: 
+----+----------+--------------+----------+-------+-----------+------------+
|    |        a |   simulation |   subset |   run |   substep |   timestep |
|----+----------+--------------+----------+-------+-----------+------------|
|  8 |  0       |            0 |        0 |     3 |         0 |          0 |
|  9 |  6.39755 |            0 |        0 |     3 |         1 |          1 |
| 10 | 12.9613  |            0 |        0 |     3 |         1 |          2 |
| 11 | 17.5493  |            0 |        0 |     3 |         1 |          3 |
+----+----------+--------------+----------+-------+-----------+------------+
```

**Comment by JEJodesty** [comment]
@BenSchZA @aclarkData @markusbkoch @matttyb80
There will be a branch for beta tests in the future

@BenSchZA
You on the team

**Comment by BenSchZA** [comment]
Thanks @JEJodesty - can confirm that solves it: https://gist.github.com/BenSchZA/c8aef315c2c25e347e2d0cd6fe489eed

**Comment by markusbkoch** [comment]
Yeah, I was gonna say randomness is tricky, all this under the hood, environment-dependent stuff leaves too much room for situations like this. 

I'd argue that the only definitive way around this might be to explicitly seed the random number generator of each run with different seeds. See example implementation in this fork from Ben's gist: https://gist.github.com/markusbkoch/135bf69e6361d3a3f84e96b6be6df971

**Comment by BenSchZA** [comment]
> Yeah, I was gonna say randomness is tricky, all this under the hood, environment-dependent stuff leaves too much room for situations like this.
> 
> I'd argue that the only definitive way around this might be to explicitly seed the random number generator of each run with different seeds. See example implementation in this fork from Ben's gist: https://gist.github.com/markusbkoch/135bf69e6361d3a3f84e96b6be6df971

Spot on, similar threads for same issue: https://stackoverflow.com/questions/12915177/same-output-in-different-workers-in-multiprocessing

**Comment by JEJodesty** [comment]
@BenSchZA @aclarkData @markusbkoch @matttyb80
hot-fixing single param scenario today

@aclarkData 
your issue is still a concern user side

**Comment by JEJodesty** [comment]
@aclarkData @matttyb80 
Its strange that this worked in windows
I will be getting windows

**Comment by JEJodesty** [comment]
solution in this branch pending merge to master by end of day
https://github.com/cadCAD-org/cadCAD/tree/issue_186

**Comment by aclarkData** [comment]
@JEJodesty Please let me know when it has been merged. Thanks

**Comment by JEJodesty** [comment]
https://pypi.org/project/cadCAD/0.4.22/
