### ISSUE TITLE
Auto generated docs from docstrings would help the community scale.

### ISSUE THREAD

**Issue by LinuxIsCool** [cadCAD-org/cadCAD#207]
I've noticed that docstrings are not implemented in some functions. They are very helpful to developers and would also enable auto-generated documentation. Anyone working on this? Thanks

**Comment by markusbkoch** [comment]
Agreed! If we can get that scoped I would support a bounty for it. Do you have previous experience with that @LinuxIsCool ? Would you like to take a shot at scoping and/or working on it?

**Comment by LinuxIsCool** [comment]
Hi Markus, I would certainly be happy to take the initiative if there was a bounty support. My team at work recently deployed automated docs using sphynx and docstrings, I can ask my colleague who did the deploy for some assistance (he is also my room mate).

**Comment by DrCatman** [comment]
tyler scheduling a design and planning call on this.

**Comment by emanuellima1** [comment]
Marked as won't do due to low priority and high time commitment.
