### ISSUE TITLE
cadCAD subset and run hierarchy

### ISSUE THREAD

**Issue by BenSchZA** [cadCAD-org/cadCAD#247]
A user of cadCAD, @rogervs, recently commented on the fact that `run == subset + 1`. This doesn't make much sense, as it doesn't provide useful additional info, instead there should be a hierarchy from `simulation` to `subset` to `run` to `timestep`, where the maximum of the former should never be larger than the maximum of the latter.

Illustrative example: an A/B test of 3 simulations, each with a parameter sweep of 3 parameter sets, 3 Monte Carlo runs, and 100 timesteps.

It should have a hierarchy of a `simulation` per config that’s simulated, `subset` per parameter set in the sweep for each `simulation`, and a `run` per Monte Carlo run for each `subset`.

In total, we'd expect 3*3*3 or 27 sets of data of 100 timesteps each.

This is probably just a bug or oversight?

**Comment by JEJodesty** [comment]
This hierarchy exists in `staging`
