### ISSUE TITLE
v0.4.27 introduces a breaking change with no backwards compatibility

### ISSUE THREAD

**Issue by BenSchZA** [cadCAD-org/cadCAD#293]
cadCAD v0.4.27 (patch update) introduces a breaking change without backwards compatibility. If cadCAD is being used in production, with semantic versioning, it would be expected that users can safely update cadCAD if only the patch version is updated. I would suggest sticking to semantic versioning and in future making v0.4.27 either a minor update with backwards compatibility, or a major update.

**Comment by JEJodesty** [comment]
@BenSchZA 
what is the breaking change?

**Comment by BenSchZA** [comment]
Cool :) Yeah that's the one. Also needing a model ID when appending more than one configuration, perhaps that could be auto generated to keep backwards compatible and remove boilerplate code.

**Comment by JEJodesty** [comment]
this issue has been resoled with v0.4.28
