### ISSUE TITLE
cadCAD Version: 0.4.28 doesn't work

### ISSUE THREAD

**Issue by VHPL-UIS** [cadCAD-org/cadCAD#301]
Hi, 
I'm using the cadCAD for a while, and I have some simulation with it on my old machine. Today, I installed it on another machine which I think the installed version is now the latest version. but it doesn't work! At first, I thought maybe it's because of different versions of python, so I made sure both machines are using the same version(3.8.10), but it didn't solve the problem. Then I checked with the tutorial code, the first one, and I got this error:
```
                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

cadCAD Version: 0.4.28
Execution Mode: local_proc
Simulation Dimensions:
Entire Simulation: (Models, Unique Timesteps, Params, Total Runs, Sub-States) = (0, 0, 0, 0, 0)
Execution Method: local_simulations
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    raw_system_events, tensor_field, sessions = simulation.execute() # The `execute()` method returns a tuple; its first elements contains the raw results
  File "/home/user/.local/lib/python3.8/site-packages/cadCAD/engine/__init__.py", line 157, in execute
    final_result = get_final_results(simulations_results, partial_state_updates, eps, sessions, remote_threshold)
  File "/home/user/.local/lib/python3.8/site-packages/cadCAD/engine/__init__.py", line 121, in get_final_results
    for sim_result, psu, ep in list(zip(simulations, psus, eps)):
TypeError: 'NoneType' object is not iterable ```

**Comment by BenSchZA** [comment]
@VHPL-UIS to confirm, you were running the following tutorial? https://github.com/BlockScience/cadCAD-Tutorials/tree/master/01%20Tutorials/robot-marbles-part-1

**Comment by BenSchZA** [comment]
@VHPL-UIS were you using Jupyter Notebook? I find it works in Lab but not Notebook, and for that reason think perhaps it's an issue with multiprocessing - that was one of the more recent refactors made to cadCAD. @JEJodesty any ideas?

**Comment by VHPL-UIS** [comment]
@BenSchZA No, I just copied the code from the notebook into a .py file and tried to run it. 
I have the 0.4.23 and it works fine.

**Comment by LinuxIsCool** [comment]
Having the same issue in jupyter lab.

**Comment by susmit** [comment]
yup having trouble running https://github.com/cadCAD-org/demos/tree/master/tutorials/robots_and_marbles/robot-marbles-part-1 with 0.4.28

**Comment by susmit** [comment]
It works fine with 0.4.23

**Comment by meiji163** [comment]
It looks like this is due to config changes in v.0.4.28. You have to use the `configs` attribute from `Experiment` instead of from `cadCAD.config`. See [here](https://github.com/cadCAD-org/cadCAD/blob/master/documentation/cadCAD-v0.4.28-Model-Upgrade-Guide.md).

**Comment by daithi-coombes** [comment]
Having same issue, with same tutorial. With help from @BenSchZA (thanks 🙏 ) I had to make some changes to the code block in the link above:
```python
from cadCAD.configuration.utils import config_sim
from cadCAD.configuration import Experiment
c = config_sim(sim_config_dict)
exp = Experiment()
exp.append_model(
    model_id = 'sys_model_1', # System Model - OPTIONAL
    initial_state = genesis_states, # System Model
    partial_state_update_blocks = partial_state_update_blocks, # System Model
#    policy_ops = ..., # System Model
    sim_configs = c, # Simulation Properties
)
configs = exp.configs
```
^ thats for block #6 of this tutorial https://github.com/cadCAD-org/demos/blob/master/tutorials/robots_and_marbles/robot-marbles-part-1/robot-marbles-part-1.ipynb

**Comment by JEJodesty** [comment]
Thanks for the update and sorry for the delay

@VHPL-UIS @susmit @daithi-coombes
**despite the title of the issue**, it entails updating not only [robot-and-marbles-part-1](https://github.com/cadCAD-org/demos/tree/master/tutorials/robots_and_marbles/robot-marbles-part-1) **to run on** 0.4.28, but also all [cadCAD demos](https://github.com/cadCAD-org/demos) 

@VHPL-UIS @susmit 
I suggest:
* updating your system model using the [CHANGELOG](https://github.com/cadCAD-org/cadCAD/blob/master/CHANGELOG.md) which contain links to documentation
* update using the [-cadcad-post-processing-modifications](https://github.com/cadCAD-org/cadCAD/blob/master/documentation/cadCAD-v0.4.28-Model-Upgrade-Guide.md#----------------cadcad-post-processing-modifications-----------) in addition to as  suggested by @meiji163
* submitting an issue to update all [cadCAD demos](https://github.com/cadCAD-org/demos) to run on 0.4.28 which includes [robot-and-marbles-part-1](https://github.com/cadCAD-org/demos/tree/master/tutorials/robots_and_marbles/robot-marbles-part-1)

@LinuxIsCool @BenSchZA
I suggest:
* if there is still an issue with jubyter lab or notebook after the steps above are complete, submit a jubyter lab and/or notebook specific issue(s) for within this repo
