### ISSUE TITLE
Why the name is not “complex adaptive dynamics for Computer-Aided Design”?

### ISSUE THREAD

**Issue by Will-Holden** [cadCAD-org/cadCAD#302]
Hello,  I know it is not an issue, but I have no place to find the answer to this question.

I want to know why the name is not “complex adaptive dynamics for Computer-Aided Design”, is there any reason to not use a "for" between "complex adaptive dynamics" and "Computer-Aided Design". 

When I introduce cadCAD to my team, my teacher asks this question/(ㄒoㄒ)/~， Could u please tell me.

**Comment by JEJodesty** [comment]
@Will-Holden 
Good question!
I believe "for" is used to suggest "Computer-Aided Design" **of** **_systems_** **with** "complex adaptive dynamics" or **having properties of** [Complex Adaptive Systems](https://en.wikipedia.org/wiki/Complex_adaptive_system)
