### ISSUE TITLE
single_proc not returning results

### ISSUE THREAD

**Issue by SeanMcOwen** [cadCAD-org/cadCAD#335]
Example of problem: https://github.com/BlockScience/PocketSimulationModel/blob/events/exploratory/cadCAD%200.5%20Test.ipynb

**Comment by SeanMcOwen** [comment]
It can also be inferred only one simulation is run from timestamps

**Comment by SeanMcOwen** [comment]
This line here seems to be the reason for only one simulation being run: https://github.com/cadCAD-org/cadCAD/blob/master/cadCAD/engine/execution.py#L29

**Comment by danlessa** [comment]
This should be solved by PR #336 

https://github.com/danlessa/cadCAD/tree/single_run_fix
