### ISSUE TITLE
cadCAD Labeling is not working post processing

### ISSUE THREAD

**Issue by SeanMcOwen** [cadCAD-org/cadCAD#359]
This error may be from improper use of some cadCAD functionality in the tooling or it may be that there needs to be a change in the underlying code. Either way, would be good to clarify as it came up on a client project.

Main problem is when entering multiple parameters and more than one monte carlo run, the labels get mismatched.

A detailed gist is here that shows the issue: https://gist.github.com/SeanMcOwen/0a7e78f2ceddf80b66ee902356b8dc3a

**Comment by danlessa** [comment]
Related to PR #360

**Comment by SeanMcOwen** [comment]
Closed by PR #360
