### ISSUE TITLE
Regression tests reference local file

### ISSUE THREAD

**Issue by BenSchZA** [cadCAD-org/cadCAD#96]
When building the Nix package derivation for cadCAD, the tests fail because of references to a local dev file `/Users/jjodesty/Projects/DiffyQ-SimCAD/simulations/external_data/output.csv` :package: 

Not sure if it's a case of committing that file, or updating those tests some other way.

**Comment by JEJodesty** [comment]
That path pertains to features in development
It needs to be replaced with something generic.
I make sure its removed for the next merge
Feel free to remove it (and submit a PR time permitting).
